name: DevSecIpd Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dumy:
    name: Build Echo Statement
    runs-on: ubuntu-latest
    steps:
      - name: Echo Building Going on
        run: echo "Building going on"

  deploy-dumy:
    name: Deploy Echo Statement
    runs-on: ubuntu-latest
    needs: build-dumy
    steps:
      - name: Echo Deploying Going on
        run: echo "Deploying going on"